<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
    'key' => 'group_5d756c588f0df',
    'title' => 'FORMULARIO',
    'fields' => array(
    array(
    'key' => 'field_5d756c5c79df2',
    'label' => 'Nombre y apellido',
    'name' => 'nombre',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
    'width' => '',
    'class' => '',
    'id' => '',
    ),
    'default_value' => '',
    'placeholder' => 'Nombre y apellido',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
    ),
    array(
    'key' => 'field_5d756c7e79df3',
    'label' => 'Correo electrónico',
    'name' => 'correo',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
    'width' => '',
    'class' => '',
    'id' => '',
    ),
    'default_value' => '',
    'placeholder' => 'Correo electrónico',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
    ),
    array(
    'key' => 'field_5d756cc879df4',
    'label' => 'Victima',
    'name' => 'victima',
    'type' => 'true_false',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
    'width' => '',
    'class' => '',
    'id' => '',
    ),
    'message' => 'Ha sido victima del conflicto?',
    'default_value' => 0,
    'ui' => 0,
    'ui_on_text' => '',
    'ui_off_text' => '',
    ),
    array(
    'key' => 'field_5d756d0b79df5',
    'label' => 'Tipo de población',
    'name' => 'tipo_de_poblacion',
    'type' => 'select',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
    'width' => '',
    'class' => '',
    'id' => '',
    ),
    'choices' => array(
    'Estudiante' => 'Estudiante',
    'Profesor' => 'Profesor',
    'Ama de casa' => 'Ama de casa',
    'Madre soltera' => 'Madre soltera',
    ),
    'default_value' => array(
    ),
    'allow_null' => 0,
    'multiple' => 0,
    'ui' => 0,
    'return_format' => 'value',
    'ajax' => 0,
    'placeholder' => '',
    ),
    ),
    'location' => array(
    array(
    array(
    'param' => 'post_type',
    'operator' => '==',
    'value' => 'correos',
    ),
    ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d7667e2d999e',
        'title' => 'Formulario Correo',
        'fields' => array(
            array(
                'key' => 'field_5d7667f11143a',
                'label' => 'Nombre y apellidos',
                'name' => 'nombre_y_apellidos',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Nombre y apellido',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d7667f81143b',
                'label' => 'Correo',
                'name' => 'correo',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Correo electrónico',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;
?>