<?php

add_action( 'init', 'cptg_custom_post_types' );
function cptg_custom_post_types()
	{
		$labels = array(
			'name' => 'Correos',
			'singular_name' => 'Correos',
			'menu_name' => 'Correos',
			'name_admin_bar' => 'Correos',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => false,
			'exclude_from_search' => true,
			'publicly_queryable' => false,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => false,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array(),
		);
		register_post_type( 'base_datos_correos', $args );
		$labels = array(
			'name' => 'Inscripciones a eventos',
			'singular_name' => 'Inscripciones a eventos',
			'menu_name' => 'Inscripciones a eventos',
			'name_admin_bar' => 'Inscripciones a eventos',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => false,
			'exclude_from_search' => true,
			'publicly_queryable' => false,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => false,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array(),
		);
		register_post_type( 'correos', $args );
        $labels = array(
			'name' => 'Galerías',
			'singular_name' => 'Galerías',
			'menu_name' => 'Galerías',
			'name_admin_bar' => 'Galerías',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'exclude_from_search' => true,
			'publicly_queryable' => false,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => false,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array(),
		);
		register_post_type( 'galerias', $args );
		$labels = array(
			'name' => 'Lugares de memoria',
			'singular_name' => 'Lugares de memoria',
			'menu_name' => 'Lugares de memoria',
			'name_admin_bar' => 'Lugares de memoria',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'exclude_from_search' => true,
			'publicly_queryable' => false,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => false,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array(),
		);
		register_post_type( 'lugares', $args );
		$labels = array(
			'name' => 'Libro de visitas',
			'singular_name' => 'Libro de visitas',
			'menu_name' => 'Libro de visitas',
			'name_admin_bar' => 'Libro de visitas',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'exclude_from_search' => true,
			'publicly_queryable' => false,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => false,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array( 'title','editor' ),
		);
		register_post_type( 'citas', $args );
		$labels = array(
			'name' => 'Programacion',
			'singular_name' => 'Programacion',
			'menu_name' => 'Programacion',
			'name_admin_bar' => 'Programacion',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'exclude_from_search' => false,
			'publicly_queryable' => true,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => true,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array( 'title','editor' ),
		);
		register_post_type( 'programacion', $args );
		$labels = array(
			'name' => 'Arte y cultura',
			'singular_name' => 'Arte y cultura',
			'menu_name' => 'Arte y cultura',
			'name_admin_bar' => 'Arte y cultura',
			'all_items' => 'All Posts',
			'add_new' => 'Add New',
			'add_new_item' => 'Add New Post',
			'edit_item' => 'Edit Post',
			'new_item' => 'New Post',
			'view_item' => 'View Post',
			'search_items' => 'Search Posts',
			'not_found' =>  'No posts found.',
			'not_found_in_trash' => 'No posts found in Trash.',
			'parent_item_colon' => 'Parent Page',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'exclude_from_search' => false,
			'publicly_queryable' => true,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_in_menu' => true,
			'show_in_admin_bar' => true,
			'has_archive' => true,
			'menu_position' => null,
			'menu_icon' => null,
			'hierarchical' => false,
			'query_var' => true,
			'can_export' => true,
			'supports' => array( 'title' ),
			'rewrite' => array( 'slug' => 'arte-y-cultura' ),
			'show_in_rest' => true
		);
		register_post_type( 'obras', $args );
		$labels = array(
			'name' => 'Tipo Evento',
			'singular_name' => 'Tipo Evento',
			'menu_name' => 'Tipo Evento',
			'all_items' => 'All Tags',
			'edit_item' => 'Edit Tag',
			'view_item' => 'View Tag',
			'update_item' => 'Update Tag',
			'add_new_item' => 'Add New Tag',
			'new_item_name' => 'New Tag Name',
			'parent_item' => 'Parent Category',
			'parent_item_colon' =>  'Parent Category',
			'search_items' => 'Search Tags',
			'popular_items' => 'Popular Tags',
			'separate_items_with_commas' => 'Separate tags with commas',
			'add_or_remove_items' => 'Add or remove tags',
			'choose_from_most_used' => 'Choose from the most used tags',
			'not_found' => 'No tags found.',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_tagcloud' => true,
			'meta_box_cb' => null,
			'show_admin_column' => false,
			'hierarchical' => true,
			'query_var' => true,
			'rewrite' => array( 'slug' => 'tipo_evento','with_front' => true,'hierarchical' => false, ),
			'sort' => false,
		);
		register_taxonomy( 'tipo_evento', array( 'programacion' ) , $args );
		$labels = array(
			'name' => 'Técnica',
			'singular_name' => 'Técnica',
			'menu_name' => 'Técnica',
			'all_items' => 'All Tags',
			'edit_item' => 'Edit Tag',
			'view_item' => 'View Tag',
			'update_item' => 'Update Tag',
			'add_new_item' => 'Add New Tag',
			'new_item_name' => 'New Tag Name',
			'parent_item' => 'Parent Category',
			'parent_item_colon' =>  'Parent Category',
			'search_items' => 'Search Tags',
			'popular_items' => 'Popular Tags',
			'separate_items_with_commas' => 'Separate tags with commas',
			'add_or_remove_items' => 'Add or remove tags',
			'choose_from_most_used' => 'Choose from the most used tags',
			'not_found' => 'No tags found.',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_tagcloud' => true,
			'meta_box_cb' => null,
			'show_admin_column' => false,
			'hierarchical' => true,
			'query_var' => true,
			'rewrite' => array( 'slug' => 'tecnica','with_front' => true,'hierarchical' => false, ),
			'sort' => false,
		);
		register_taxonomy( 'tecnica', array( 'obras' ) , $args );
		$labels = array(
			'name' => 'Disciplina',
			'singular_name' => 'Disciplina',
			'menu_name' => 'Disciplina',
			'all_items' => 'All Tags',
			'edit_item' => 'Edit Tag',
			'view_item' => 'View Tag',
			'update_item' => 'Update Tag',
			'add_new_item' => 'Add New Tag',
			'new_item_name' => 'New Tag Name',
			'parent_item' => 'Parent Category',
			'parent_item_colon' =>  'Parent Category',
			'search_items' => 'Search Tags',
			'popular_items' => 'Popular Tags',
			'separate_items_with_commas' => 'Separate tags with commas',
			'add_or_remove_items' => 'Add or remove tags',
			'choose_from_most_used' => 'Choose from the most used tags',
			'not_found' => 'No tags found.',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_tagcloud' => true,
			'meta_box_cb' => null,
			'show_admin_column' => false,
			'hierarchical' => true,
			'query_var' => true,
			'rewrite' => array( 'slug' => 'disciplina','with_front' => true,'hierarchical' => false, ),
			'sort' => false,
			'show_in_rest' => true
		);
		register_taxonomy( 'disciplina', array( 'obras' ) , $args );
		$labels = array(
			'name' => 'Autor',
			'singular_name' => 'Autor',
			'menu_name' => 'Autor',
			'all_items' => 'All Tags',
			'edit_item' => 'Edit Tag',
			'view_item' => 'View Tag',
			'update_item' => 'Update Tag',
			'add_new_item' => 'Add New Tag',
			'new_item_name' => 'New Tag Name',
			'parent_item' => 'Parent Category',
			'parent_item_colon' =>  'Parent Category',
			'search_items' => 'Search Tags',
			'popular_items' => 'Popular Tags',
			'separate_items_with_commas' => 'Separate tags with commas',
			'add_or_remove_items' => 'Add or remove tags',
			'choose_from_most_used' => 'Choose from the most used tags',
			'not_found' => 'No tags found.',
		);
		$args = array(
			'labels' => $labels,
			'public' => true,
			'show_ui' => true,
			'show_in_nav_menus' => true,
			'show_tagcloud' => true,
			'meta_box_cb' => null,
			'show_admin_column' => false,
			'hierarchical' => true,
			'query_var' => true,
			'rewrite' => array( 'slug' => 'autor','with_front' => true,'hierarchical' => false, ),
			'sort' => false,
			'show_in_rest' => true
		);
		register_taxonomy( 'autor', array( 'obras' ) , $args );
	}

?>